### ISSUE TITLE
Upload test flight package

### ISSUE THREAD

**Issue by dominik-weber** [Microsoft/windows-dev-center-vsts-extension#13] opened 2016-09-12 01:13 UTC
My current approach to distribution is uploading a test flight (aka beta) package using continuous deployment from VSTS and later (after some manual QA testing) promoting the package to production release.
This works perfectly with the deployment extensions for Apple AppStore and Google Play. However this scenario seems unsupported in the Windows Dev Center extension, as it currently only allows uploading/creating production submissions.

**Comment by kp101090** [comment] 2016-09-13 02:11
Thank you very much for bringing it up @dominik-weber. We do have good news for you. We are actively working on adding flighting support and you will soon be able to exercise your scenario using extension!

**Comment by dominik-weber** [comment] 2016-10-10 23:17
@kp101090 Is there a reason why the PR was not merged/deployed yet? I'm looking forward to using this feature.

**Comment by elendil326** [comment] 2016-12-19 15:34
The PR has been merged and the feature is now supported. Closing this thread.

**Closed by elendil326** 2016-12-19 15:34 UTC
Labels: suggestion

**Comment by dominik-weber** [comment] 2017-01-02 12:13
I'm still having some issues with this feature. As you can see here the old packages are not removed from the submission, only new packages are added. If I manually create a submission from the dev portal old packages are removed automatically.
![image](https://cloud.githubusercontent.com/assets/1771927/21588997/15abd996-d0ed-11e6-84d2-8a8a5a1cef2b.png)

**Comment by dominik-weber** [comment] 2017-01-15 00:58
@elendil326 @kp101090 any news regarding this? Should I open a new issue?

**Comment by ChristopheLav** [comment] 2017-01-15 08:29
@dominik-weber, actually this is by design (from what I understood). However #PR27 is recently submitted to allow old package deletion during a submission.

**Comment by dominik-weber** [comment] 2017-01-15 16:54
@ChristopheLav sorry, didn't see that. Thanks! Please merge ;)
