### ISSUE TITLE
Error on pushing flight

### ISSUE THREAD

**Issue by jamers99** [microsoft/windows-dev-center-vsts-extension#94] opened 2020-09-02 12:46 UTC
We haven't changed anything and now we are getting this error when pushing an update to a flight:

```
Obtaining app information...
Obtaining flight resource for flight Beta in app 9NTSH9RQ89KR
Creating flight submission...
Submission https://developer.microsoft.com/en-us/dashboard/apps/9NTSH9RQ89KR/submissions/1152921505691304024 was created successfully
Deleting old packages...
Updating package delivery options...
Updating flight submission...
Creating zip file...
Uploading zip file...
Successfully uploaded file!
Committing flight submission...
##[error]Status 500: {"code":"InternalServerError","data":[],"details":[],"innererror":{"code":"UnknownInternalFailure","data":[],"details":[],"message":"The service has encountered an unknown internal server error: "},"message":"An internal server error occurred while processing the operation.","source":"Ingestion Api"} CorrelationId: 0a0e4430-8d6e-4c12-9f35-3fb0db39d063
```

**Comment by jdub403** [comment] 2020-09-02 14:34
We are having the same issue as well.  Started around 6-7pm mountain time yesterday.

**Comment by radujipa** [comment] 2020-09-02 16:20
We are seeing the same problem across our org. Can we get a resolution for this ASAP please?

**Comment by radujipa** [comment] 2020-09-02 16:27
@louis-wuitton Is there a quick rollback / fix that can be done here? Is it possibly an issue with the Store API?

**Comment by louis-wuitton** [comment] 2020-09-02 16:35
This looks like a store side issue. I will reach out to the Store team

**Comment by louis-wuitton** [comment] 2020-09-02 16:41
In the meantime please do a retry and see if it helps.

**Comment by radujipa** [comment] 2020-09-02 17:00
@louis-wuitton Appreciate the escalation to the Store team and hope this gets resolved quickly. As this poses a delivery risk for our organisation, we may need to further raise this through OEM channels tomorrow. In the meantime, retries are not solving the issue - have done plenty by now.

Happy to help with any logs or examples or anything else here.

**Comment by jamers99** [comment] 2020-09-02 17:10
Same here. Retries give the same error.

**Comment by louis-wuitton** [comment] 2020-09-02 17:31
From what the Store team told me, they do have a clue on what might be going on and they are working on it

**Comment by louis-wuitton** [comment] 2020-09-02 19:22
Hi guys, the windows store team told me the issue should be mitigated. Please give it a try and see how it goes.

**Comment by radujipa** [comment] 2020-09-02 19:32
Many thanks @louis-wuitton! I've got a build past Flight and it's now going to the Live submission. Appreciate the speedy fix from the Team! 🙏

**Comment by louis-wuitton** [comment] 2020-09-02 19:37
Much kudos to the windows store team for fixing the issue!

Closing this issue since it has been mitigated.

**Closed by louis-wuitton** 2020-09-02 19:37 UTC

**Comment by jdub403** [comment] 2020-09-03 15:43
Glad to hear its fixed.  Seems to be good for us as well.

Can we get confirmation on the root cause?
