### ISSUE TITLE
Cannot Create/Edit Azure DevOps Service Connection

### ISSUE THREAD

**Issue by jdub403** [microsoft/windows-dev-center-vsts-extension#87] opened 2020-06-26 23:42 UTC
Since the Azure DevOps extension was updated yesterday 6/25/2020 at 5:10 pm mountain (v0.9.31) our existing connection no longer works.  I cannot edit it and get one of the same errors that exist in the issue log.

**Error from existing connection:** 

Status 401:
{"error":"invalid_client","error_description":"AADSTS7000216: 'client_assertion', 'client_secret' or 'request' is required for the 'client_credentials' grant type.

**Issue when creating new connection:**
As a workaround I tried to create a new service connection but that does not work either, I get an error regarding Service Connection Authorization Cannot be Null.  To get around this I disabled the preview feature in azure devops for the service connection interface and still get the same error.

![image](https://user-images.githubusercontent.com/29606256/85908853-22062800-b7d4-11ea-9ba1-57bbd12ac8e4.png)

This has blocked us and now we cannot upload to the store through Azure DevOps.

**Comment by bangskimus** [comment] 2020-06-29 15:03
Is there an update on how to fix the issue?

**Comment by louis-wuitton** [comment] 2020-06-29 17:59
Looked into this. This was caused by a regression from last update. I just added a fix for this.

**Comment by louis-wuitton** [comment] 2020-06-29 21:10
Created PR to address this issue: https://github.com/microsoft/windows-dev-center-vsts-extension/pull/88

**Comment by bangskimus** [comment] 2020-06-29 21:25
@louis-wuitton - I'm able to create a new service connection and deploy to the Microsoft Store.

**Comment by jamers99** [comment] 2020-06-30 12:44
The update (0.9.33) still has issues. I am unable to publish to the store!

I got the following error this morning when we tried to publish to the store:
![image](https://user-images.githubusercontent.com/20806279/86127163-7566c780-baad-11ea-8acb-ed7addc00348.png)

I went into our Service Connection and found most of the values blanked out and a new Username and Password field:
![image](https://user-images.githubusercontent.com/20806279/86127366-beb71700-baad-11ea-8005-c5ffde439780.png)

I tried to fill out all the fields, but I got this error:
![image](https://user-images.githubusercontent.com/20806279/86127415-d2627d80-baad-11ea-837e-036990624742.png)

What do I need to do to get this resolved?

**Comment by jamers99** [comment] 2020-06-30 12:54
I deleted the service connection and recreated it, then it worked.

**Comment by iabkohler** [comment] 2020-06-30 16:02
This doesn't work for me.  Deleted service connection. Created new service connection.  Flight task received error:

 "error":"invalid_request","error_description":"AADSTS90002: Tenant 'undefined' not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID.

The tenant ID is the same one used in the service connection that was deleted.

**Comment by jamers99** [comment] 2020-06-30 20:59
Getting the same thing when trying to publish to a flight (formatted)
```
Status 400: 
{
  "error":"invalid_request",
  "error_description":"AADSTS90002: Tenant 'undefined' not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID. Check with your subscription administrator.\r\nTrace ID: 56c83271-0d21-4067-af79-247f8f430000\r\nCorrelation ID: cb8fcb21-c50d-40c8-9160-32028fbae8ac\r\nTimestamp: 2020-06-30 20:54:58Z",
  "error_codes":[90002],
  "timestamp":"2020-06-30 20:54:58Z","trace_id":"56c83271-0d21-4067-af79-247f8f430000",
  "correlation_id":"cb8fcb21-c50d-40c8-9160-32028fbae8ac",
  "error_uri":"https://login.microsoftonline.com/error?code=90002"
}
```

@louis-wuitton what can we do to get around this?

**Comment by louis-wuitton** [comment] 2020-07-02 15:03
Closing this issue

**Closed** 2020-07-02 15:03 UTC
